# Generated by Django 5.2.11 on 2026-03-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingsession',
            name='minutes_read',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='readingsession',
            name='pages_read',
            field=models.PositiveIntegerField(),
        ),
    ]
