# Generated by Django 5.2.11 on 2026-04-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_readingsession_minutes_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.URLField(blank=True),
        ),
    ]
