# Generated by Django 5.2.11 on 2026-05-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='status',
            field=models.CharField(choices=[('reading', 'Reading'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('wishlist', 'Wishlist')], max_length=20),
        ),
    ]
